<Project Sdk="Microsoft.NET.Sdk">

	<PropertyGroup>
		<OutputType>Exe</OutputType>
		<TargetFramework>net10.0</TargetFramework>
		<ImplicitUsings>enable</ImplicitUsings>
		<Nullable>enable</Nullable>
	</PropertyGroup>

	<ItemGroup>
		<ProjectReference Include="..\..\src\Rappd.Data\Rappd.Data.csproj" />
		<ProjectReference Include="..\..\src\Rappd.Data.Shared\Rappd.Data.Shared.csproj" />
		<ProjectReference Include="..\..\src\Rappd.Data.Shared\Rappd.Data.Shared.csproj" OutputItemType="Analyzer" ReferenceOutputAssembly="false" />
		<ProjectReference Include="..\..\src\Rappd.Data.Generators\Rappd.Data.Generators.csproj" OutputItemType="Analyzer" ReferenceOutputAssembly="false" />
	</ItemGroup>

</Project>
